"""empty message

Revision ID: d1f119ba7de5
Revises: 2df86673e509
Create Date: 2024-05-23 23:19:32.359953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f119ba7de5'
down_revision: Union[str, None] = '2df86673e509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('query', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'query')
    # ### end Alembic commands ###
