"""empty message

Revision ID: 14ff749886f5
Revises: d6f08d5e2030
Create Date: 2024-05-23 00:30:15.378447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14ff749886f5'
down_revision: Union[str, None] = 'd6f08d5e2030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('uuid', sa.Uuid(), nullable=False))
    op.add_column('image', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('image', 'payload')
    op.add_column('post', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('product', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('subject', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'created_at')
    op.drop_column('product', 'created_at')
    op.drop_column('post', 'created_at')
    op.add_column('image', sa.Column('payload', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('image', 'created_at')
    op.drop_column('image', 'uuid')
    # ### end Alembic commands ###
