"""empty message

Revision ID: 45fc6f158bf0
Revises: e3b4539365aa
Create Date: 2024-05-23 01:36:57.492118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45fc6f158bf0'
down_revision: Union[str, None] = 'e3b4539365aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
