"""empty message

Revision ID: 45c43963089d
Revises: 0262e692d3f6
Create Date: 2024-05-17 16:41:16.255495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c43963089d'
down_revision: Union[str, None] = '0262e692d3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('image', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('image', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('image', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('image', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
