"""empty message

Revision ID: 7af551024b10
Revises: b0c15b4ccaab
Create Date: 2024-05-25 14:35:47.763146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af551024b10'
down_revision: Union[str, None] = 'b0c15b4ccaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.drop_column('post', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('post', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
